name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      CR_USERNAME: felipecrs
      DOCKERHUB_USERNAME: felipecassiors
      IMAGE_NAME: jenkins-agent-dind

    steps:
      - uses: actions/checkout@v2

      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ env.CR_USERNAME }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: ${{ env.CR_USERNAME }}/${{ env.IMAGE_NAME }}
          add_git_labels: true
          tag_with_ref: true
          tag_with_sha: true

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          add_git_labels: true
          tag_with_ref: true
          tag_with_sha: true

      # Only runs when commit is pushed to master
      - if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ env.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
